name: project_9
description: "Project 9 UAL 2023/24"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_commons: ^0.6.1
  google_mlkit_face_detection: ^0.9.0
  image_picker: ^1.0.8
  http: ^1.2.1
  camera: ^0.9.4+5
  path: ^1.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/LOGO_SOMBRA.png
    - assets/images/profile.jpg
    - assets/images/face_logo.png
